name: flutter_admin_tarot
description: "Admin dashboard Flutter để quản lý người dùng & kết quả bói Tarot"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # HTTP & API
  http: ^1.2.1

  # State Management
  provider: ^6.1.2

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Advanced UI Components
  data_table_2: ^2.5.9

  # Animation & Responsive
  animations: ^2.0.11
  flutter_screenutil: ^5.9.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # Date Formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
